app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// Route::get('/bridge/latest_crawl', 'DumpController@latest_crawl');

Route::get('/bridge/{method}/{url}', 'DumpController@bridge');
Route::group(['middleware' => ['auth']], function(){

	// BRIDGE
	
	
	// LOCATION
	Route::get('/location/{lat}/{lng}', 'DumpController@location');
 	// DUMP
	Route::get('/dump/all', 'DumpController@all');
	Route::get('/dump/recent_post', 'DumpController@recent_post');
	Route::get('/dump/rdm', 'DumpController@randomLat');
	Route::get('/dump/stream', 'DumpController@stream');
	Route::post('/dump/influencer', 'DumpController@influencer'); // request: [topic]
	Route::post('/dump/person-detail', 'DumpController@persondetail'); 
	Route::post('/dump/topperson/', 'DumpController@topperson'); // request: [topic, dateStart, dateStop]
	Route::post('/dump/demograph/', 'DumpController@demograph'); // request: [topic, dateStart, dateStop]
	Route::post('/dump/sentiment/', 'DumpController@sentiment'); // request: [topic, dateStart, dateStop]
	Route::get('/dashboard/index', function(){return redirect('v2/index');});

	// DASBHOARD
	/*Route::get('/dashboard/index', 'DashboardController@index');
	Route::get('/dashboard/influencer/{topic}', 'DashboardController@influencer');
	Route::get('/dashboard/influencer', 'DashboardController@influencer');
	Route::get('/dashboard/top-person/{topic}', 'DashboardController@topperson');
	Route::get('/dashboard/top-person', 'DashboardController@topperson');
	Route::get('/dashboard/sentiment/{topic}', 'DashboardController@sentiment');
	Route::get('/dashboard/sentiment', 'DashboardController@sentiment');
	Route::get('/dashboard/demography', 'DashboardController@demography');
	Route::get('/dashboard/demography/{topic}', 'DashboardController@demography');
	Route::get('/dashboard/mapping', 'DashboardController@mapping');
	Route::get('/dashboard/mapping/{topic}', 'DashboardController@mapping');
	Route::get('/dashboard/compare', 'DashboardController@compare');
	Route::get('/selectTopic/{topic}', 'DashboardController@selectTopic');
	Route::get('/dashboard/peak', 'DashboardController@peak');*/


	// TOPIC
	/*Route::resource('/dashboard/topic', 'TopicController');
	Route::get('/dashboard/topic/delete/{id}', ['as' => 'dashboard.topic.delete', 'uses' => 'TopicController@destroy']);*/

	// CRAWL
	/*Route::resource('/dashboard/crawl', 'CrawlController');*/
	

	// USER
	/*Route::resource('/dashboard/user', 'UserController');
	Route::get('/dashboard/log', 'UserController@log');

	Route::get('/dashboard/delete/{id}', ['as' => 'dashboard.user.delete', 'uses' => 'UserController@destroy']);
	Route::get('/dashboard/profile', ['as' => 'dashboard.user.profile', 'uses' => 'UserController@profile']);

	Route::post('/dashboard/profile/twitter/update', ['as' => 'twitter.update', 'uses' => 'SocialAuthController@updateTwitter']);*/

	// OBJECT
	/*Route::resource('/dashboard/object/all', 'ObjectController');
	Route::get('/dashboard/object/all/delete/{id}', ['as' => 'dashboard.object.delete', 'uses' => 'ObjectController@destroy']);*/

	// SOCIAL OBJECT
	/*Route::resource('/dashboard/object/social', 'SocialObjectController');
	Route::get('/dashboard/object/social/delete/{id}', ['as' => 'dashboard.object.social.delete', 'uses' => 'SocialObjectController@destroy']);*/
	
	// DOWNLOAD
	// Route::get('/dashboard/download/{type}', 'DownloadController@view');
	Route::get('/download/{menu}/{id}/{type}', 'DownloadController@download');
 	/*
	MISSING ROUTE REDIRECTOR
	*/

	/*Route::get('/dashboard', function(){
		return redirect('/dashboard/index');
	});
	Route::get('/dashboard/object', function(){
		return redirect('dashboard/object/all');
	});*/
	Route::get('/login_token=random', function () {
	    return view('template.auth.login');
	}); 

	/*Route::get('/dashboard/download', function(){
		return redirect('dashboard');
	});*/
	
	// STAT
	Route::get('/stat/cpu_load', 'StatController@cpuLoad');
	Route::get('/stat/storage', 'StatController@storage');
	Route::get('/stat/totalcrawled', 'StatController@total_crawled');
	Route::get('/stat/test', 'StatController@test');

	// THIRD-PARTY
	Route::get('/facebook/connect', 'SocialAuthController@fbConnect');
	Route::get('/facebook/callback', 'SocialAuthController@fbCallback');
	Route::get('/facebook/is_expired', 'SocialAuthController@fbIsExpired');

	/*Route::get('/', function(){
		return redirect('/dashboard/index');
	});*/

	// UI.VERSION.2
	Route::get('/', function(){
		return redirect('/v2/index');
	});
	Route::get('/v2/', function(){
		return redirect('/v2/index');
	});

	Route::get('v2/index', 'DashboardController@main');
 	Route::get('v2/help', function(){
		return view('v2.page.dashboard.help', ['selectedTab' => 'help']);
	});

	// Route sementara EXpose
	Route::get('v2/expose', 'DashboardController@expose');

	Route::get('v2/statistic', function(){
		return view('v2.page.dashboard.statistic', ['selectedTab' => 'statistic', 'crawl_queue' => DB::table('crawl_queues')->orderBy('id', 'desc')->get()]);
	});
	Route::get('v2/stream', function(){
		return view('v2.page.dashboard.stream', ['selectedTab' => 'stream']);
	});
	Route::get('v2/analyze', function(){
		Session::flash('notification',['error' => 'Select topic you want to analyze']);
		return redirect('/');
	});
		Route::get('v2/download/{type}', 'DownloadController@view',['selectedTab' => 'stream']);

	Route::get('v2/download/{menu}/{id}/{type}', 'DownloadController@download',['selectedTab' => 'stream']);

	Route::get('v2/analyze/{keyword}', function($keyword){
		$existedKeyword = DB::table('crawl_queues')->where('keyword', str_replace('%20', ' ', $keyword))->get();
		$objects = DB::table('objects')->get();
		if (count($existedKeyword) > 0){
			return view('v2.page.analyze', ['selectedTab' => 'none', 'topic' => $keyword, 'objects' => $objects, 'current' => $existedKeyword[0]]);
		}
		else 
			return redirect('v2/index');
	});
	Route::resource('v2/configuration', 'ObjectController');
	Route::resource('v2/object', 'ObjectController');
	Route::resource('v2/social', 'SocialObjectController');
	Route::resource('v2/user', 'UserController');
	Route::resource('v2/topic', 'TopicController');
	Route::get('/v2/profile', 'UserController@profileV2');
	Route::get('/v2/loguser', 'UserController@logusermodal');
	Route::get('/v2/streamportalfront', 'DashboardController@streamportalfront');
	Route::get('/v2/configuration/social/delete/{id}', ['as' => 'v2.social.delete', 'uses' => 'SocialObjectController@destroy']);
	Route::get('/v2/configuration/object/delete/{id}', ['as' => 'v2.object.delete', 'uses' => 'ObjectController@destroy']);
	Route::get('/v2/configuration/user/delete/{id}', ['as' => 'v2.user.delete', 'uses' => 'UserController@destroy']);
	Route::post('/v2/profile/twitter/update', ['as' => 'v2.twitter.update', 'uses' => 'SocialAuthController@updateTwitter']);
});
Route::auth();

app/Http/Controllers/DashboardController.php
<?php

/*
PT. TRIKARYA TECHNOLOGIES
* FRANSISKUS GUSTI NGURAH DWIKA SETIAWAN * 
* I PUTU PRADNYANA *
* MUHAMMAD GHOZIE MANGGALA *
* REYHAN ARIEF *

Script for view the analytic
function : 
__construct() : set initial value of global variable $data. Global variable can be called with $this method ($this->data)
index() : show interface of dashboard
selectTopic($topic) : select topic
influencer($topic = 'noTopic') :  show interface for view the influencer of a topic
topperson($topic = 'noTopic') : show interface for view the topperson of a topic
demography($topic = 'noTopic' : show interface for view the demography of a topic
sentiment($topic = 'noTopic') : show interface for view the sentiment of a topic
mapping($topic = 'noTopic') : show interface for view the mapping of a topic
compare() : show interface for compare the two topic
peak() : show peak time of every topic
*/

namespace App\Http\Controllers;
use Session;
use Illuminate\Http\Request;
use App\crawl_queue;
use App\object;
use App\log;
use App\Http\Requests;
use App\User as user;
use Auth;
class DashboardController extends Controller
{
    //
    protected $data;
    public function __construct(){
    	if (empty(Session::get('selectedTopic')))
            $this->data['topic'] = "noTopic";
        else 
            $this->data['topic'] = Session::get('selectedTopic');
        $this->data['latest_topic'] = crawl_queue::orderBy('id', 'dsec')->first();
        $this->data['crawl_object'] = object::count();
    }
    public function index(){
    	$data = $this->data;
        $data['content'] = crawl_queue::with('user', 'crawl_features')->orderBy('id', 'desc')->get();
        $data['objects'] = object::all();

        // Page title and breadcrumb
        $data['page_title'] = "Dashboard";
        $data['breadcrumb'][0]['title'] = "Dashboard";
        $data['breadcrumb'][0]['link'] = url('/dashboard');

    	return view('page.dashboard.index', compact('data'));
    }
    public function streamportalfront(){
        $data = $this->data;
        $data['content'] = crawl_queue::with('user', 'crawl_features')->orderBy('id', 'desc')->get();
        $data['objects'] = object::all();

        // Page title and breadcrumb
        $data['page_title'] = "Dashboard";
        $data['breadcrumb'][0]['title'] = "Dashboard";
        $data['breadcrumb'][0]['link'] = url('/v2/index');

        return view('v2.page.dashboard.stream.modal', compact('data'));
    }

    public function main()
    {
	//dd(Session::get('toastr'));
        $data['latest_topic'] = crawl_queue::orderBy('id', 'dsec')->first();
        $data['crawl_object'] = object::count();
        
        $data['topics'] = crawl_queue::with('user', 'crawl_features')->orderBy('id', 'desc')->get();
	//dd($data['topics']);
        $data['objects'] = object::orderBy('id', 'desc')->get();
        $selectedTab = 'dashboard';
        return view('v2.page.dashboard.index', compact('data', 'selectedTab'));
    }

    public function expose(){
        $data['topics'] = crawl_queue::with('crawl_features')->orderBy('id', 'asc')->get();
        $data['objects'] = object::orderBy('id', 'desc')->get();
        return view('v2.page.dashboard.expose', ['selectedTab' => 'expose', 'data' => $data]);
    }

    public function influencer($topic = 'noTopic'){
    	$data = $this->data;
        
        // Page title and breadcrumb
        $data['page_title'] = "Influencer";
        $data['breadcrumb'][0]['title'] = "Dashboard";
        $data['breadcrumb'][0]['link'] = url('/dashboard');
        $data['breadcrumb'][1]['title'] = "Influencer";
        $data['breadcrumb'][1]['link'] = url('/dashboard/influencer');

    	if (empty(Session::get('selectedTopic'))){
            $toastr = ['type' => 'error', 'message' => 'No Topic Selected'];
    		Session::set('toastr', $toastr);
    		return redirect('/');
    	}
        if (!empty($topic)){
            $data['topic'] = $topic;
            $log = new log;
            $log->action = 'view';
            $log->table = 'influencer';
            $log->reference = $topic;
            $log->user_id = Auth::user()->id;
            $log->save();
            return view('page.dashboard.influencer', compact('data'));
        }
    }
    public function topperson($topic = 'noTopic'){
    	$data = $this->data;

        // Page title and breadcrumb
        $data['page_title'] = "Top Person";
        $data['breadcrumb'][0]['title'] = "Dashboard";
        $data['breadcrumb'][0]['link'] = url('/dashboard');
        $data['breadcrumb'][1]['title'] = "Top Person";
        $data['breadcrumb'][1]['link'] = url('/dashboard/top-person');

    	if (empty(Session::get('selectedTopic'))){
    		$toastr = ['type' => 'error', 'message' => 'No Topic Selected'];
            Session::set('toastr', $toastr);
    		return redirect('/')->with($data['page_title'], $data['breadcrumb']);
    	}
    	if (!empty($topic)){
    		$data['topic'] = $topic;
            $data['objects'] = object::all();
            $data['topic'] = $topic;
            $log = new log;
            $log->action = 'view';
            $log->table = 'top-person';
            $log->reference = $topic;
            $log->user_id = Auth::user()->id;
            $log->save();
    		return view('page.dashboard.topperson', compact('data'));
    	}
    }

    public function selectTopic($topic){
    	if (!empty($topic)){
    		Session::set('selectedTopic', $topic);
            Session::flash('toastr', ['type' => 'success', 'message' => 'Topic Selected: '.$topic]);
        }
    	return redirect('dashboard/influencer/'.$topic);
    }

    public function demography($topic = 'noTopic')
    {
        $data = $this->data;

        // Page title and breadcrumb
        $data['page_title'] = "Demography";
        $data['breadcrumb'][0]['title'] = "Dashboard";
        $data['breadcrumb'][0]['link'] = url('/dashboard');
        $data['breadcrumb'][1]['title'] = "Demography";
        $data['breadcrumb'][1]['link'] = url('/dashboard/demography');

        if (empty(Session::get('selectedTopic'))){
            $toastr = ['type' => 'error', 'message' => 'No Topic Selected'];
            Session::set('toastr', $toastr);
            return redirect('/')->with($data['page_title'], $data['breadcrumb']);
        }
    	
        $data['topic'] = $topic;
        $log = new log;
        $log->action = 'view';
        $log->table = 'demography';
        $log->reference = $topic;
        $log->user_id = Auth::user()->id;
        $log->save();
    	return view('page.dashboard.demography', compact('data'));
    }

    public function sentiment($topic = 'noTopic'){
        $data = $this->data;

        // Page title and breadcrumb
        $data['page_title'] = "Sentiment";
        $data['breadcrumb'][0]['title'] = "Sentiment";
        $data['breadcrumb'][0]['link'] = url('/dashboard');
        $data['breadcrumb'][1]['title'] = "Sentiment";
        $data['breadcrumb'][1]['link'] = url('/dashboard/sentiment');

        if (empty(Session::get('selectedTopic'))){
            $toastr = ['type' => 'error', 'message' => 'No Topic Selected'];
            Session::set('toastr', $toastr);
            return redirect('/')->with($data['page_title'], $data['breadcrumb']);
        }
        $data['topic'] = $topic;
        $log = new log;
        $log->action = 'view';
        $log->table = 'sentiment';
        $log->reference = $topic;
        $log->user_id = Auth::user()->id;
        $log->save();
        return view('page.dashboard.sentiment', compact('data'));
    }

    public function mapping($topic = 'noTopic'){
        if (empty(Session::get('selectedTopic'))){
            $toastr = ['type' => 'error', 'message' => 'No Topic Selected'];
            Session::set('toastr', $toastr);
            return redirect('/')->with($data['page_title'], $data['breadcrumb']);
        }
        $data = $this->data;
        // Page title and breadcrumb
        $data['page_title'] = "Mapping";
        $data['breadcrumb'][0]['title'] = "Mapping";
        $data['breadcrumb'][0]['link'] = url('/dashboard');
        $data['breadcrumb'][1]['title'] = "Mapping";
        $data['breadcrumb'][1]['link'] = url('/dashboard/mapping');
        return view('page.dashboard.mapping', compact('data'));
    }

    public function compare(){
        $data = $this->data;
        // Page title and breadcrumb
        $data['page_title'] = "Compare";
        $data['breadcrumb'][0]['title'] = "Compare";
        $data['breadcrumb'][0]['link'] = url('/dashboard');
        $data['breadcrumb'][1]['title'] = "Compare";
        $data['breadcrumb'][1]['link'] = url('/dashboard/compare');
        $data['content'] = crawl_queue::orderBy('id', 'desc')->get();
        return view('page.dashboard.compare', compact('data'));
    }

    public function peak(){
        $data = $this->data;
        // Page title and breadcrumb
        $data['page_title'] = "Compare";
        $data['breadcrumb'][0]['title'] = "Compare";
        $data['breadcrumb'][0]['link'] = url('/dashboard');
        $data['breadcrumb'][1]['title'] = "Compare";
        $data['breadcrumb'][1]['link'] = url('/dashboard/compare');
        $data['content'] = crawl_queue::orderBy('id', 'desc')->get();
        return view('page.dashboard.peak', compact('data'));
    }

    
}

resources/views/v2/page/dashboard/index.blade.php
@extends('v2.template.index')
 
@section('main-content')
<div class="row-fluid">
  <div class="span12">
    <ul class="breadcrumb-beauty">
      <li>
        <a href="{{ URL::to('/v2/index') }}"><span class="fs1" aria-hidden="true" data-icon="&#xe002;"></span> Dashboard</a>
      </li>
      <li>
        <a href="{{ URL::to('/v2/index') }}">Main</a>
      </li>
    </ul>
  </div>
</div>

<br>

@include('v2.template.top_graph')
<!-- latest topic list -->
<div class="row-fluid">
  <div class="span12">
    <div class="widget">
      <div class="widget-header">
      <div class="title">
      <span class="fs1" aria-hidden="true" data-icon="&#xe1cd;"></span> Topik List | Silahkan memilih topik berikut atau  
      <button class="badge badge-success input-bottom-margin standardModalButton" style="border: none" href="#standardModal" role="button" data-toggle="modal" url="{{route('v2.topic.create')}}">
            Tambahkan Topik
      </button>
      </div>
      <div class="tools pull-right">
      </div>
      </div>
      <div class="widget-body">
         <!-- tabel topik -->
        <div class="row-fluid" >
        <?php
        $topicCounter = 0;
        ?>
        @foreach($data['topics'] as $print)
          @if(++$topicCounter%4 == 3)
          </div>
          <div class="row-fluid">
          @endif
          <div class="span3" style="margin-left:4px">
            <div class="widget widget-border">
              <div class="widget-body">
                <div class="current-stats">
                  <h4 class="text-warning" style="font-size:15px">{{$print->keyword}}</h4>
                  <p>Crawl Start:&nbsp;<b>{{$print->created_at}}</b></p>
                  <div class="type">
                    <span class="fs1 text-warning fa fa-search-plus fs1 fa-3x" aria-hidden="true"  ></span>
                  </div>
                </div>
              </div>
              <div class="widget ">
                <center>Object :
                @foreach($print->crawl_features as $cf)
                    @if ($cf['object']['logo'] != '')
                      <img src="{{asset('/userFile/'.$cf['object']['logo'])}}" title="{{$cf['object']['name']}}" style="max-width: 16px; max-height: 16px">
                    @endif
                @endforeach
                </center>
              </div>
              <center>
                <a class="btn btn-warning2 popover-pop" href="{{URL::to('v2/analyze/'.str_replace(' ', '%20', $print->keyword))}}">
                  <i class="fa fa-sign-in"></i>&nbsp;pilih topik
                </a>
              </center> 
              <br>
            </div>
          </div>
        @endforeach

        </div>
      </div>   
    </div>
<!-- CRAWL STAT -->
<div class="row-fluid">
  <div class="span6">
    <div class="plain-header">
      <h4 class="title">
       <span class="fs1 fa fa-line-chart" aria-hidden="true" ></span> Crawl Stats
      </h4>
    </div>
    <div class="row-fluid">
      <div class="span6">
        <div class="widget less-bottom-margin widget-border widget-border">
          <div class="widget-body">
            <div class="current-stats">
              <h4 class="text-info">{{$data['latest_topic']->keyword}}</h4>
              <p>Latest Topic</p>
              <div class="type">
                <span class="fs1 arrow text-info" aria-hidden="true" data-icon="&#xe048;"></span> 
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="widget less-bottom-margin widget-border">
          <div class="widget-body">
            <div class="current-stats">
              <h4 class="text-success" id="storage">~ GB</h4>
              <p>Storage Used</p>
              <div class="type">
                <span class="fs1 fa fa-hdd-o fa-3x arrow" aria-hidden="true"></span> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6">
        <div class="widget widget-border">
          <div class="widget-body">
            <div class="current-stats">
              <h4 class="text-warning">{{$data['crawl_object']}}</h4>
              <p>Crawl Object</p>
              <div class="type">
                <span class="fs1 arrow text-warning" aria-hidden="true" data-icon="&#xe077;"></span> 
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="widget widget-border">
          <div class="widget-body">
            <div class="current-stats">
              <h4 id="total"> ~ </h4>
              <p>Total Items Crawled</p>
              <div class="type">
                <span class="fs1 fa fa-search-plus fa-3x arrow" aria-hidden="true"></span> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="span6">
    <div class="plain-header">
      <h4 class="title">
        <span class="fs1 fa fa-clock-o" aria-hidden="true" ></span>&nbsp;Crawl Latest Logs
      </h4>
    </div>
    <div class="row-fluid">
      <div class="span6">
        <div class="widget less-bottom-margin widget-border">
          <div class="widget-body">
            <div class="current-stats">
              <h4 class="text-success">Portal Berita</h4>
              <p>View Crawl Logs</p>
              <div class="type">
                <span class="fs1 arrow fa fa-newspaper-o fa-3x text-success" aria-hidden="true"></span> 
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="span6">
        <div class="widget less-bottom-margin widget-border">
          <div class="widget-body">
            <div class="current-stats">
              <h4 class="text-info">Facebook</h4>
              <p>View Crawl Logs</p>
              <div class="type">
                <span class="fs1 arrow fa fa-facebook fa-3x text-info" aria-hidden="true"></span> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6">
        <div class="widget widget-border">
          <div class="widget-body">
            <div class="current-stats">
              <h4 class="text-warning" style="color:#0084b4">Twitter</h4>
              <p>View Crawl Logs</p>
              <div class="type">
                <span class="fs1 arrow fa fa-twitter fa-3x text-warning" style="color:#0084b4" aria-hidden="true"  ></span> 
              </div>
            </div>
          </div>
        </div>
      </div>
       
    </div>
  </div>
</div>

@endsection

 @section('custom-footer')
<script type="text/javascript">
  $.ajax({
      url: "{{ URL::to('/stat/storage') }}",
      type: "GET",
      dataType: "html",
      success: function (data) {  
          $('#storage').html(data);
      },
  });
  $.ajax({
      url: "{{ URL::to('/stat/totalcrawled') }}",
      type: "GET",
      dataType: "html",
      success: function (data) {  
        data = jQuery.parseJSON(data);
        $('#total').html(data.total);
      },
  });
  var dtl = [];
  for (var i = 0; i < 30; i++){
    dtl.push(0);
  }
  setInterval(function(){
    $.get("{{URL::to('stat/cpu_load')}}").done(function(response){
      dtl.shift();
      dtl.push(response);
      showDTL();
    });
    function showDTL(){
      var newDTL = [];
      for (var i = 0; i < dtl.length; i++){
        newDTL.push([i+1, dtl[i]]);
      }
      $(function() {
        var data = [{
          label: "Server Stats (Core CPU/Second)",
          data: newDTL
        }];
        var options = {
          series: {
            lines: { show: true,
              lineWidth: 2,
              fill: false,
              },
            points: { show: true, 
              lineWidth: 2 
              },
            shadowSize: 0
          },
          grid: { hoverable: true, 
            clickable: true, 
            tickColor: "#eeeeee",
            borderWidth: 0
          },
          legend: {
            noColumns: 3
          },
          colors: ["#3b5a9b", "#d3503e"],
           xaxis: {ticks:12, tickDecimals: 0},
           yaxis: {ticks:3, tickDecimals: 0},
          selection: {
            mode: "x"
          }
        };

        var placeholder = $("#selectionCharts");

        var plot = $.plot(placeholder, data, options);
      });
    }
  }, 1000);
</script>
<script src="{{asset('v2/js/custom-index.js')}}"></script>
 @endsection